import React from 'react';

import css from './About.module.css';
import aboutImg from '../../img/AboutImg.png';

import cross from '../../img/svg/cross.svg';

function About() {
  return (
    <section className={css.aboutSection}>
      <h2 className={css.aboutTitle}>
        a Story that started with{' '}
        <span className={css.aboutTitleOneSimple}>
          one simple
          <br /> ape
        </span>
      </h2>
      <p className={css.aboutDiscription}>
        WHO GOT
        <br /> FED UP WITH BORING
        <br /> AND HYPOCRITIC
        <br /> COMMONPLACE THIS IS
        <br /> HOW THE IDEA OF
        <br /> ESCAPING AND DYNAMIC
        <br /> JOURNEY ON THE YACHT
      </p>

      <img src={cross} alt="cross" className={css.AboutCros} />

      <p className={css.aboutNote}>
        EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
        RANDOMLY GENERATED BY USERS
      </p>
      <img src={aboutImg} alt="About ape" className={css.aboutImg} />
    </section>
  );
}

export default About;
