import React from 'react';

import css from './About.module.css';

import cross from '../../img/svg/cross.svg';

function About() {
  return (
    <section className={css.aboutSection} id="ABOUT">
      <h2 className={css.aboutTitle}>
        a Story that started with
        <span className={css.aboutTitleOneSimple}>
          one simple
          <br /> ape
        </span>
      </h2>

      <p className={css.aboutDiscription}>
        WHO GOT
        <br /> FED UP WITH BORING
        <br /> AND HYPOCRITIC
        <br /> COMMONPLACE THIS IS
        <br /> HOW THE IDEA OF
        <br /> ESCAPING AND DYNAMIC
        <br /> JOURNEY ON THE YACHT
      </p>

      <div className={css.aboutTabletThumb}>
        <div>
          {' '}
          <h2 className={css.aboutTitleDesctop}>
            a Story <br />
            that <br />
            started <br /> with one
            <span className={css.aboutTitleOneSimpleTable}>simple ape</span>
          </h2>
          <div className={css.aboutNoteThumb}>
            <img src={cross} alt="cross" className={css.aboutCrosTablet} />
            <p className={css.aboutNoteTablet}>
              EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
              ARE RANDOMLY GENERATED BY USERS
            </p>
          </div>
        </div>
        <p className={css.aboutDiscriptionDesctop}>
          WHO GOT FED UP WITH BORING
          <br /> AND HYPOCRITIC COMMONPLACE
          <br /> THIS IS HOW THE IDEA OF
          <br /> ESCAPING AND DYNAMIC
          <br /> JOURNEY ON THE <br /> YACHT
        </p>
      </div>

      <img src={cross} alt="cross" className={css.aboutCros} />
      <p className={css.aboutNote}>
        EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
        RANDOMLY GENERATED BY USERS
      </p>

      <div className={css.aboutImg}></div>
    </section>
  );
}

export default About;
